site_name: Documentation as a code
site_description: The guide to handle beraucracy as a developer
docs_dir: src
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - sql
        - python

markdown_extensions:
    - def_list
    - pymdownx.tasklist
    - pymdownx.snippets
    - toc:
        permalink: "#"
        baselevel: 2
