name: CI

on:
  pull_request: {}
  push:
    branches: ["master"]
    
jobs:
  github-pages:
    name: Github Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      # - name: Install python3.10
      #   run: >
      #     apt update

      #     apt install -y python3
      - name: Ensure pip
        run: >
          python3 --version

          python3 -m ensurepip

      - name: Install requirements.txt
        run: >
          pip install -r requirements.txt
      - name: Build docs
        run: >
          mkdocs build
      - name: tar build
        run: >
          tar -zcvf ${{ runner.temp }}/github_pages site/
      - uses: actions/upload-artifact@main # or actions/upload-pages-artifact
        with:
          name: github-pages
          path: ${{ runner.temp }}/github_pages
          retention-days: "1"
      - name: Deploy to pages
        uses: actions/deploy-pages@v1
        id: github-pages

